servicebot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  head_tilt_position_controller:
    # type: effort_controllers/JointPositionController
    type: position_controllers/JointPositionController
    joint: head_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  head_pan_position_controller:
    # type: effort_controllers/JointPositionController
    type: position_controllers/JointPositionController
    joint: head_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
