TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: -0.2
  max_rot_vel: 0.7
  min_rot_vel: -0.7
  # max_vel_theta: 1.0
  # min_in_place_vel_theta: 0.4
  max_trans_vel: 0.5 # choose slightly less than the base's capability
  min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity

  sim_time: 2
  # sim_granularity: 0.01
  occdist_scale: 0.03

  acc_lim_x: 1
  acc_lim_y: 0.0
  acc_lim_th: 3.2

  controller_frequency: 10.0
# holonomic_robot: false
