obstacle_range: 9
obstacle_range: 10
# footprint: [[0.2, 0.15], [0.2, -0.15], [-0.2, -0.15], [-0.2, 0.15]]
footprint: [[0.2, 0.25], [0.2, -0.25], [-0.2, -0.25], [-0.2, 0.25]]
inflation_radius: 0.4
observation_sources: laser_scan_sensor
# laser_scan_sensor: {sensor_frame: lidar_frame, data_type: LaserScan, topic: servicebot/scan, marking: true, clearing: true}
laser_scan_sensor:
  sensor_frame: lidar_frame
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
  inf_is_valid: true
  raytrace_range: 100.0
